import { Component, DestroyRef, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink, ActivatedRoute } from '@angular/router';
import { forkJoin } from 'rxjs';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { DocumentationApiService } from '../../core/api/documentation-api.service';
import { DocumentContent, NavigationNode, SearchResult } from '../../core/models/content.models';
import { MarkdownService } from '../../core/services/markdown.service';

@Component({
  imports: [RouterLink, FormsModule],
  template: `<section class="docs-shell"><aside class="sidebar"><a class="docs-home" routerLink="/docs">Documentation</a><label>Search <input [(ngModel)]="query" (keyup.enter)="search()" placeholder="Search documentation" /></label>@if (results().length) {<div class="results">@for (item of results(); track item.slug) {<a [routerLink]="docLink(item.slug)"><strong>{{ item.title }}</strong><small>{{ item.snippet }}</small></a>}</div>}@for (group of navigation(); track group.title) {<section><h3>{{ group.title }}</h3>@for (item of group.children; track item.slug) {<a [class.current]="item.slug === document()?.slug" [routerLink]="docLink(item.slug!)">{{ item.title }}</a>}</section>}</aside><article class="document">@if (document(); as item) {<p class="eyebrow">{{ item.category }} · {{ item.version }}</p><div class="markdown" [innerHTML]="html()"></div><nav class="pager">@if(item.previous){<a [routerLink]="docLink(item.previous.slug)">← {{ item.previous.title }}</a>}@if(item.next){<a [routerLink]="docLink(item.next.slug)">{{ item.next.title }} →</a>}</nav>} @else {<p class="loading">Loading documentation…</p>}</article><aside class="toc">@for (item of headings(); track item.id) {<a [class.level3]="item.level === 3" [href]="'#' + item.id">{{ item.text }}</a>}</aside></section>`,
  styles: `.docs-shell{width:min(1440px,100%);margin:auto;display:grid;grid-template-columns:240px minmax(0,760px) 190px;gap:2rem;padding:2rem;min-height:calc(100vh - 130px)}.sidebar{border-right:1px solid var(--rk-border);padding-right:1rem}.docs-home{display:block;font-weight:800;color:var(--rk-text);margin-bottom:1rem}.sidebar label{display:grid;gap:.3rem;font-size:.82rem;color:var(--rk-text-secondary)}input{width:100%;border:1px solid var(--rk-border);border-radius:.35rem;padding:.45rem;background:var(--rk-surface);color:var(--rk-text)}.sidebar section{margin-top:1.4rem}.sidebar h3{font-size:.78rem;text-transform:uppercase;letter-spacing:.08em;color:var(--rk-text-secondary);margin-bottom:.45rem}.sidebar section>a,.results a{display:block;padding:.27rem .4rem;border-radius:.3rem;font-size:.9rem;color:var(--rk-text-secondary)}.sidebar a.current,.sidebar a:hover{color:var(--rk-primary);background:var(--rk-surface-secondary)}.results{margin-top:.5rem;border:1px solid var(--rk-border);border-radius:.4rem}.results small{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.document{min-width:0;padding-bottom:2rem}.loading{color:var(--rk-text-secondary)}.toc{border-left:1px solid var(--rk-border);padding-left:1rem;align-self:start;position:sticky;top:86px}.toc a{display:block;color:var(--rk-text-secondary);font-size:.85rem;margin:.35rem 0}.toc .level3{padding-left:.8rem}.pager{display:flex;justify-content:space-between;gap:1rem;border-top:1px solid var(--rk-border);padding-top:1.5rem;margin-top:3rem}.markdown h1{font-size:2.5rem}.markdown h2{margin-top:2.4rem;font-size:1.5rem}.markdown p,.markdown li{color:var(--rk-text-secondary)}.markdown pre{overflow:auto;padding:1rem;background:var(--rk-code-bg);color:#e6edf7;border-radius:.45rem}.markdown code{font-family:ui-monospace,SFMono-Regular,Consolas,monospace}.markdown p code{background:var(--rk-surface-secondary);padding:.12rem .3rem;border-radius:.2rem}.markdown blockquote{margin:1.5rem 0;padding:.75rem 1rem;border-left:3px solid var(--rk-primary);background:var(--rk-surface-secondary)}@media(max-width:1020px){.docs-shell{grid-template-columns:220px minmax(0,1fr)}.toc{display:none}}@media(max-width:700px){.docs-shell{display:block;padding:1.25rem}.sidebar{border:0;border-bottom:1px solid var(--rk-border);padding:0 0 1rem;margin-bottom:1.5rem}.sidebar section{display:none}.pager{flex-direction:column}.markdown h1{font-size:2rem}}`,
})
export class DocsComponent {
  private readonly api = inject(DocumentationApiService); private readonly route = inject(ActivatedRoute); private readonly router = inject(Router); private readonly destroyRef = inject(DestroyRef); readonly markdown = inject(MarkdownService);
  readonly navigation = signal<NavigationNode[]>([]); readonly document = signal<DocumentContent | null>(null); readonly results = signal<SearchResult[]>([]); query = '';
  readonly html = computed(() => this.document() ? this.markdown.render(this.document()!.content) : '');
  readonly headings = computed(() => this.document() ? this.markdown.headings(this.document()!.content) : []);
  constructor() { this.route.paramMap.pipe(takeUntilDestroyed(this.destroyRef)).subscribe(() => this.load()); }
  docLink(slug: string) { const { language, version } = this.context(); return ['/docs', language, version, ...slug.split('/')]; }
  search() { const { language, version } = this.context(); if (this.query.trim().length > 1) this.api.search(this.query, language, version).subscribe({ next: value => this.results.set(value), error: () => this.results.set([]) }); }
  private load() { const { language, version, slug } = this.context(); this.document.set(null); this.results.set([]); forkJoin({ navigation: this.api.getNavigation(language, version), document: this.api.getDocument(language, version, slug) }).subscribe({ next: value => { this.navigation.set(value.navigation); this.document.set(value.document); document.title = `${value.document.title} — RelaxKonOS Documentation — RelaxKon`; }, error: () => this.document.set(null) }); }
  private context() { const language = this.route.snapshot.paramMap.get('language') ?? 'en-US'; const version = this.route.snapshot.paramMap.get('version') ?? 'latest'; const parts = this.router.url.split('?')[0].split('/').filter(Boolean); return { language, version, slug: parts.slice(3).join('/') || 'getting-started/introduction' }; }
}
