import { Component, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import { I18nService } from '../../core/i18n/i18n.service';

@Component({
  imports: [RouterLink],
  template: `<section class="hero"><div class="container hero-grid"><div><p class="eyebrow">RelaxKonOS</p><h1>A modern remote workspace operating environment.</h1><p class="lead">Local UI rendering, persistent applications, and server-managed workspaces—without turning the desktop into a pixel stream.</p><div class="actions"><a routerLink="/products/relaxkonos" class="button primary">{{ i18n.t('viewProduct') }}</a><a routerLink="/docs" class="button secondary">{{ i18n.t('getStarted') }}</a></div></div><aside class="architecture"><p>LOCAL CLIENT</p><strong>UI · Windows · Input</strong><i>↕ protocol</i><p>REMOTE SERVER</p><strong>Workspace · Runtime · Storage</strong></aside></div></section><section class="page"><div class="container"><p class="eyebrow">Designed for continuity</p><h2>A desktop experience that follows your workspace.</h2><div class="card-grid"><article class="card"><h3>Local rendering</h3><p>The interface is rendered on the client for responsive interaction and platform-native presentation.</p></article><article class="card"><h3>Persistent services</h3><p>Remote runtimes and workspace services can continue beyond a single client connection.</p></article><article class="card"><h3>Clear boundaries</h3><p>Protocol contracts keep applications, client UI, and server capabilities independently evolvable.</p></article></div></div></section>`,
  styles: `.hero{padding:6.5rem 0 5rem;background:radial-gradient(circle at 82% 25%,color-mix(in srgb,var(--rk-primary) 16%,transparent),transparent 30%)}.hero-grid{display:grid;grid-template-columns:1.5fr .8fr;gap:3rem;align-items:center}.hero h1{max-width:11ch}.actions{display:flex;gap:.75rem;margin-top:1.7rem}.architecture{padding:1.7rem;border:1px solid var(--rk-border);border-radius:1rem;background:var(--rk-surface);box-shadow:var(--rk-shadow)}.architecture p{font-size:.73rem;font-weight:800;letter-spacing:.1em;color:var(--rk-primary);margin:.4rem 0}.architecture strong{display:block}.architecture i{display:block;font-style:normal;color:var(--rk-text-secondary);margin:1.6rem 0;text-align:center}@media(max-width:760px){.hero{padding:4rem 0}.hero-grid{grid-template-columns:1fr;gap:2rem}.hero h1{max-width:none}}`,
})
export class HomeComponent { readonly i18n = inject(I18nService); }
